# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'companysetup.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from gsheetsconnect import Ui_GSheetsConnectWindow
class Ui_CompanySetupWindow(object):
    def openGConnect(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_GSheetsConnectWindow()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 823)
        MainWindow.setStyleSheet("background-color: rgb(245, 224, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica 45 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 771, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-left-color: rgb(255, 113, 57);")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 461, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/Company_Setup.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.companysetup_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.companysetup_Btn.setGeometry(QtCore.QRect(270, 720, 261, 41))
        self.companysetup_Btn.clicked.connect(self.openGConnect)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.companysetup_Btn.setFont(font)
        self.companysetup_Btn.setObjectName("companysetup_Btn")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 580, 281, 91))
        font = QtGui.QFont()
        font.setFamily("Helvetica 45 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(550, 670, 251, 121))
        font = QtGui.QFont()
        font.setFamily("Helvetica 45 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(510, 70, 281, 121))
        font = QtGui.QFont()
        font.setFamily("Helvetica 45 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(510, 170, 281, 121))
        font = QtGui.QFont()
        font.setFamily("Helvetica 45 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(510, 270, 281, 141))
        font = QtGui.QFont()
        font.setFamily("Helvetica 45 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(510, 420, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica 45 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(510, 490, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica 45 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Now, in the same Google Sheets file as the student responses, create a new sheet directly after. Here, create a table of the number of seats (for each session) at each table for each company like the following:"))
        self.companysetup_Btn.setText(_translate("MainWindow", "Press here to continue."))
        self.label_7.setText(_translate("MainWindow", "Make sure this sheet of company data is DIRECTLY after the form responses."))
        self.label_8.setText(_translate("MainWindow", "You can also go to https://tinyurl.com/y3rvm4hh to see this sheet or refer to the transition doc."))
        self.label_9.setText(_translate("MainWindow", "Essentially, this will serve as a database so the program knows how many seats are remaining at each table. "))
        self.label_10.setText(_translate("MainWindow", "Create 4 Columns like the image on the left: Company, Entree, Dessert, Majors Wanted"))
        self.label_11.setText(_translate("MainWindow", "For the Company column, fill this with the name of the companies. NOTE: make sure when you enter the company name there is no space after. This program checks for EXACT matches, and extra spaces or letters results in an error."))
        self.label_12.setText(_translate("MainWindow", "For the Majors Wanted column, fill with the majors that the company is interested in. "))
        self.label_13.setText(_translate("MainWindow", "For the Entree and Dessert Columns, fill this with the maximum number of students allowed at each table."))

